In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulRY SIZE
voc_size = 10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### OneHot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr
## the values values shows that the our words are present on that index

[[6439, 8735, 4212, 2448],
 [6439, 8735, 4212, 3803],
 [6439, 6868, 4212, 6927],
 [8974, 9594, 9672, 5752, 6479],
 [8974, 9594, 9672, 5752, 9033],
 [3316, 6439, 3133, 4212, 7437],
 [6949, 5478, 6452, 5752]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np


In [ ]:
sent_length=8
## padding - pre => adding zeros in front.
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6439 8735 4212 2448]
 [   0    0    0    0 6439 8735 4212 3803]
 [   0    0    0    0 6439 6868 4212 6927]
 [   0    0    0 8974 9594 9672 5752 6479]
 [   0    0    0 8974 9594 9672 5752 9033]
 [   0    0    0 3316 6439 3133 4212 7437]
 [   0    0    0    0 6949 5478 6452 5752]]


In [ ]:
## feature representation - word2Vec
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 588ms/step


array([[[ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,
          0.046523  ,  0.02197106,  0.01854273,  0.01800772,
          0.00955521,  0.00772785],
        [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,
          0.046523  ,  0.02197106,  0.01854273,  0.01800772,
          0.00955521,  0.00772785],
        [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,
          0.046523  ,  0.02197106,  0.01854273,  0.01800772,
          0.00955521,  0.00772785],
        [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,
          0.046523  ,  0.02197106,  0.01854273,  0.01800772,
          0.00955521,  0.00772785],
        [-0.02252183, -0.02524459,  0.01682082, -0.03847891,
         -0.02209505,  0.00649121,  0.02578017, -0.03120048,
         -0.00633347, -0.00237729],
        [-0.03189309,  0.00277991,  0.01171715, -0.01250647,
          0.00025207,  0.01976358,  0.02485422, -0.03703479,
         -0.00982036,  0.0368509 ],
        [-0.04202514,  0.01275611, -0.01318287,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 6439, 8735, 4212, 2448])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 76ms/step


array([[ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,  0.046523  ,
         0.02197106,  0.01854273,  0.01800772,  0.00955521,  0.00772785],
       [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,  0.046523  ,
         0.02197106,  0.01854273,  0.01800772,  0.00955521,  0.00772785],
       [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,  0.046523  ,
         0.02197106,  0.01854273,  0.01800772,  0.00955521,  0.00772785],
       [ 0.02782682, -0.0338748 , -0.01809856,  0.02143023,  0.046523  ,
         0.02197106,  0.01854273,  0.01800772,  0.00955521,  0.00772785],
       [-0.02252183, -0.02524459,  0.01682082, -0.03847891, -0.02209505,
         0.00649121,  0.02578017, -0.03120048, -0.00633347, -0.00237729],
       [-0.03189309,  0.00277991,  0.01171715, -0.01250647,  0.00025207,
         0.01976358,  0.02485422, -0.03703479, -0.00982036,  0.0368509 ],
       [-0.04202514,  0.01275611, -0.01318287,  0.0264038 ,  0.04021749,
         0.00481929,  0.01705035,  0.0025273 